version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  rabbit:
    image: rabbitmq
    volumes:
      - rabbit_data:/var/lib/rabbitmq/data/
    ports:
      - "15672:15672"
  web:
    build: .
    command: honcho start
    volumes:
      - .:/build
    ports:
      - "8000:8000"
      - "5555:5555"
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbit
  migration:
    image: python:3
    command: python manage.py migrate --noinput
    volumes:
      - .:/build
    depends_on:
      - db
volumes:
  postgres_data:
  rabbit_data: