# Generated by Django 3.0.5 on 2020-04-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-id']},
        ),
    ]
